swagger: "2.0"
info:
  description: ""
  version: "0.1.0"
  title: "Pricify API"

host: "0.0.0.0:3300"
basePath: "/api/v1"

tags:
  - name: "users"
    description: "Operations about user"
  - name: "user-permissions"
    description: "Operations about user permissions"
  - name: "files"
    description: "Uploads and other things with files"

schemes:
  # - "https"
  - "http"

paths:

  /user/create:
    post:
      tags:
        - "users"
      summary: "Create user"
      operationId: "createuser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Created user object"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              username:
                type: "string"
              email:
                type: "string"
                format: "email"
      responses:
        "200":
          description: "Created user object"
          schema:
            type: "object"
            properties:
              id:
                type: "string"
                format: "uuid"
              created_at:
                type: "string"
                format: "date-time"

  /user/delete:
    post:
      tags:
        - "users"
      summary: "Delete user"
      operationId: "deleteuser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Deleted user object"
          required: true
          schema:
            type: "object"
            properties:
              id:
                type: "string"
                format: "uuid"
      responses:
        "200":
          description: "Deleted user info"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
              message:
                type: "string"

  /user/login:
    post:
      tags:
        - "users"
      summary: "Authenticate a user"
      operationId: "loginuser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Created user object"
          required: true
          schema:
            type: "object"
            properties:
              username:
                type: "string"
              password:
                type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              username:
                type: "string"
              password:
                type: "string"
        "400":
          description: "Invalid status value"

  /user/logout:
    post:
      tags:
        - "users"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        default:
          description: "successful operation"

  /upload:
    post:
      tags:
        - "files"
      summary: "uploads an image"
      description: ""
      operationId: "uploadFile"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: "formData"
          description: "Additional data to pass to server"
          required: false
          type: "string"
        - name: "file"
          in: "formData"
          description: "file to upload"
          required: false
          type: "file"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"

securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

definitions:

  CreatedObject:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      created_at:
        type: "string"
        format: "date-time"

  UpdatedObject:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      updated_at:
        type: "string"
        format: "date-time"

  DeletedObject:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      deleted_at:
        type: "string"
        format: "date-time"

  User:
    type: "object"
    properties:
      username:
        type: "string"
      name:
        type: "string"
      email:
        type: "string"

  UserLogin:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"

  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
