version: '3'

services:
  api:
    build: './api'
    volumes:
      - './api/html/:/usr/share/nginx/html/'
    ports:
      - '3300:80'
  swaggereditor:
    build: './swaggereditor'
    ports:
      - '2200:8080'
    depends_on:
      - 'api'
